= 6. Install AAP2

icon:clock-o[Duration: 30-60 Minutes] Duration: 30-60 minutes

Finally time to run the installer though the actual configuration steps in the prior two modules were quite relatively straightforward.

[NOTE]
====
This lab comes with two terminals so you can launch the installer in one terminal and keep an eye on the output whilst using the other to explore the processes and directory structures being deployed on the Containerized AAP2 host, reachable via `ssh aap2`

If you are swapping back and forth between the 2 terminals remember to ensure that both terminals have the `ANSIBLE_COLLECTIONS_PATH` set correctly.

[source,sh,role=execute,subs=attributes+]
----
export ANSIBLE_COLLECTIONS_PATH=/home/devops/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64/collections
----

By default `ansible` would not be able to find the collections inside the bundled installer, hence the need to set this explicitly.
====

[Installation]
== Installation

. Ensure you are in the bundled installer directory
+

[source,sh,role=execute,subs=attributes+]
----
cd ~/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64
----

. Ensure your ANSIBLE_COLLECTIONS_PATH is set correctly
+

[source,sh,role=execute,subs=attributes+]
----
export ANSIBLE_COLLECTIONS_PATH=/home/devops/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64/collections
----

[TIP]
====
Occasionally at events like conferences network issues arise, and this can be unpredictable. If you have issues running the above command and losing the connection and in turn breaking the install you can use `tmux` as a workaround.

. Use `tmux` to create a tmux session which you can re-attach to.
+

[source,sh,role=execute,subs=attributes+]
----
tmux new -t aap2
----

. You can re-attach to tmux via:
+

[source,sh,role=execute,subs=attributes+]
----
tmux attach -t aap2
----
Hopefully, however, this scenario will not arise.
====

. Run the installer

+

[source,sh,role=execute,subs=attributes+]
----
ansible-playbook -i inventory \
    ansible.containerized_installer.install \
    -e GUID={guid}
----
+
[NOTE]
====
The final argument is unique to our configuration, as mentioned in the prior module. The `-e GUID={guid}` allows us to dereference the `GUID` var we used in our config-as-code Postinstall files. 
====
+



== Exploring the Installation Process

While the installer is running, keep an eye on it and you will see the flow of installation. Notice the `ansible.containerized_installer` collection is used for installation and can be explored from the installer directory `collections/ansible_collections/ansible`

. In parallel, use the other terminal to explore the installation, ssh onto the Containerized AAP2 host
+

[source,sh,role=execute,subs=attributes+]
----
ssh aap2
----

. As the installation proceeds explore it with the following commands:
+

[source,sh,role=execute,subs=attributes+]
----
tree -L 4 aap
----
+

.Sample Output
[source,texinfo]
----
aap
└── containers
    ├── podman
    ├── storage
    └── xxxxxxx.xxxx
----
+

[WARNING]
====
If you don't see the same output as printed before, wait a couple of seconds and try again
====

[CHALLENGE]
====
*Eigth Challenge:* Based on the previous command output solve the challenge: https://red-hat-summit-connect-hands-on-day-2024.ctfd.io/challenges#8%20-%20Paste%20the%20last%20file%20name,%20replace%20the%20xxxxxx.xxxx%20with%20the%20right%20value-41[Eight Challenge Link,window=read-later]
====


Containerized AAP2 Installer configures the above directory structure in the `ansible_user` account, in our case the `ec2-user`. In Production, it would be a good practice to create a dedicated service account for this purpose.

. Explore the `podman` images with `podman image ls` and later in the installation process with `podman ps`
+

+

[source,sh,role=execute,subs=attributes+]
----
podman image ls
----
+

.Sample Output
[source,texinfo]
----
REPOSITORY                                                                 TAG         IMAGE ID
     CREATED      SIZE
registry.redhat.io/ansible-automation-platform-25/eda-controller-ui-rhel8  latest      4b62ac633
268  4 weeks ago  482 MB
registry.redhat.io/ansible-automation-platform-25/hub-web-rhel8            latest      2f6b603ff
b2b  4 weeks ago  480 MB
registry.redhat.io/ansible-automation-platform-25/hub-rhel8                latest      480b644e2
729  4 weeks ago  697 MB
registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8     latest      a798fe430
891  4 weeks ago  553 MB
registry.redhat.io/ansible-automation-platform-25/controller-rhel8         latest      3de4a8039
84f  4 weeks ago  918 MB
registry.redhat.io/ansible-automation-platform-25/gateway-rhel8            latest      0f91335fd
02d  4 weeks ago  517 MB
registry.redhat.io/ansible-automation-platform-25/gateway-proxy-rhel8      latest      f9b868bc5
4d1  4 weeks ago  295 MB
registry.redhat.io/ansible-automation-platform-25/receptor-rhel8           latest      f146268bd
cf7  4 weeks ago  346 MB
registry.redhat.io/rhel8/redis-X                                           latest      1e3c9ff29
583  5 weeks ago  301 MB
----

[WARNING]
====
If you don't see the same output as printed before, wait a few minutes and try again
====

[CHALLENGE]
====
*Ninth Challenge:* Based on the previous command output, wait until the `redis-XX` image appears to solve the challenge: https://red-hat-summit-connect-hands-on-day-2024.ctfd.io/challenges#Paste%20the%20Redis%20container%20image%20version-42[Ninth Challenge Link,window=read-later]
====


. As the installation progresses the various containers run by `podman` as `systemd` services will come to life.
+

[source,sh,role=execute,subs=attributes+]
----
podman ps
----
+

.Sample Output (late in the installation with all containers running)
[source,texinfo]
----
CONTAINER ID  IMAGE
COMMAND               CREATED         STATUS         PORTS       NAMES
b1f1de0e3519  registry.redhat.io/rhel8/redis-6:latest
run-redis             31 minutes ago  Up 31 minutes              redis-unix
d2f065c8fd9d  registry.redhat.io/rhel8/redis-6:latest
run-redis             30 minutes ago  Up 21 minutes              redis-tcp
a164fb918c2a  registry.redhat.io/ansible-automation-platform-25/gateway-proxy-rhel8:latest
/usr/bin/envoy --...  19 minutes ago  Up 17 minutes              automation-gateway-proxy
fbf095e30270  registry.redhat.io/ansible-automation-platform-25/gateway-rhel8:latest
/usr/bin/supervis...  19 minutes ago  Up 17 minutes              automation-gateway
50b6d52921d5  registry.redhat.io/ansible-automation-platform-25/receptor-rhel8:latest
/usr/bin/receptor...  17 minutes ago  Up 17 minutes              receptor
2641a41b48fc  registry.redhat.io/ansible-automation-platform-25/controller-rhel8:latest
/usr/bin/launch_a...  16 minutes ago  Up 10 minutes              automation-controller-rsyslog
968edfc8178e  registry.redhat.io/ansible-automation-platform-25/controller-rhel8:latest
/usr/bin/launch_a...  15 minutes ago  Up 10 minutes              automation-controller-task
9e536c24c911  registry.redhat.io/ansible-automation-platform-25/controller-rhel8:latest
/usr/bin/launch_a...  15 minutes ago  Up 10 minutes              automation-controller-web
26d6ca6242ee  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
gunicorn --bind 1...  9 minutes ago   Up 8 minutes               automation-eda-api
13ec8310f32a  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
daphne --bind 127...  9 minutes ago   Up 7 minutes               automation-eda-daphne
c7d27393d224  registry.redhat.io/ansible-automation-platform-25/eda-controller-ui-rhel8:latest
/bin/sh -c nginx ...  9 minutes ago   Up 7 minutes               automation-eda-web
a9d85cb813ce  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
aap-eda-manage rq...  9 minutes ago   Up 7 minutes               automation-eda-worker-1
208128ff9c02  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
aap-eda-manage rq...  9 minutes ago   Up 7 minutes               automation-eda-worker-2
72eb908cdcdf  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
aap-eda-manage rq...  8 minutes ago   Up 7 minutes               automation-eda-activation-worke
r-1
283d95115938  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
aap-eda-manage rq...  8 minutes ago   Up 7 minutes               automation-eda-activation-worke
r-2
8d50e4d49894  registry.redhat.io/ansible-automation-platform-25/eda-controller-rhel8:latest
aap-eda-manage sc...  8 minutes ago   Up 7 minutes               automation-eda-scheduler
4f1b74ac6a76  registry.redhat.io/ansible-automation-platform-25/hub-rhel8:latest
pulpcore-api --na...  7 minutes ago   Up 4 minutes               automation-hub-api
cf6ed27f9d55  registry.redhat.io/ansible-automation-platform-25/hub-rhel8:latest
pulpcore-content ...  6 minutes ago   Up 4 minutes               automation-hub-content
f4caa51341ab  registry.redhat.io/ansible-automation-platform-25/hub-web-rhel8:latest
/bin/sh -c nginx ...  6 minutes ago   Up 4 minutes               automation-hub-web
46ad271f5270  registry.redhat.io/ansible-automation-platform-25/hub-rhel8:latest
pulpcore-worker       6 minutes ago   Up 4 minutes               automation-hub-worker-1
4931f5365d5d  registry.redhat.io/ansible-automation-platform-25/hub-rhel8:latest
pulpcore-worker       6 minutes ago   Up 4 minutes               automation-hub-worker-2
----

[NOTE]
====
The installation process will take around *20* more minutes beyond this point. You can grab a coffee/bewerage of your choice, or ask some questions to the Lab monitors. After your coffee break, you can continue with the lab instructions, no matter if the installation has not completed, we need only the `Automation Gateway`, and the `Automation Controller` to be ready for the next steps.
====

== Summary

We have now, hopefully, successfully run the deployer and installed Containerized AAP2.

The next module will guide us through an exploration of running a `job_template` on our new installation but feel free to explore the components:


[cols="2,3,2,2"]
|===
|Service |URL |Login |Password

| Automation Gateway
|https://aap2.{subdomain}[https://aap2.{subdomain},window=read-later]
|`admin`
|`r3dh4t1!`

|===